# Generated by Django 3.0.5 on 2020-08-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullthrottle_task', '0002_auto_20200807_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiods',
            name='end_time',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='activityperiods',
            name='start_time',
            field=models.CharField(max_length=150),
        ),
    ]
